@extends('layouts.app')

@section('content')
    <livewire:stock.create
        :stockGroups="$stockGroups"
        :units="$units"
        :defaultUnit="$defaultUnit"
        :manufacturers="$manufacturers"
        :discountsh="$discountsh"
        :vats="$vats"
        :types="$types"
        :currencies="$currencies"
        :partners="$partners"
        :accounts="$accounts"
        :stocks="$stocks"
        :registers1="$registers1"
        :registers2="$registers2"
        :registers3="$registers3"
        :registers4="$registers4"
        :registers5="$registers5"
        :departments="$departments"
        :persons="$persons"
        :projects="$projects"
        :pacTypes="$pacTypes"
    />
@endsection
